# Generated by Django 3.0.2 on 2020-01-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesreviewsystem', '0002_cinema_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_name', models.TextField()),
                ('email', models.EmailField(max_length=60)),
                ('address', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='cinema',
            old_name='date',
            new_name='release_date',
        ),
        migrations.AddField(
            model_name='cinema',
            name='director',
            field=models.TextField(blank=True, null=True),
        ),
    ]
