# Generated by Django 3.0.2 on 2020-01-30 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviesreviewsystem', '0003_auto_20200129_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='name',
        ),
        migrations.AddField(
            model_name='cinema',
            name='cinema_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viewers',
            name='cinema_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moviesreviewsystem.Cinema'),
        ),
    ]
