# Generated by Django 3.0.2 on 2020-01-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesreviewsystem', '0004_auto_20200129_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewers',
            name='viewer_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
