# Generated by Django 3.0.2 on 2020-01-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesreviewsystem', '0005_auto_20200129_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewers',
            name='viewer_name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
