# Generated by Django 3.0.2 on 2020-01-30 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesreviewsystem', '0006_auto_20200129_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewers',
            name='viewer_name',
        ),
    ]
