# Generated by Django 3.0.2 on 2020-01-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesreviewsystem', '0007_remove_viewers_viewer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewers',
            name='viewer_name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
