# Generated by Django 3.0.2 on 2020-01-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesreviewsystem', '0008_viewers_viewer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewers',
            name='address',
        ),
        migrations.RemoveField(
            model_name='viewers',
            name='email',
        ),
        migrations.RemoveField(
            model_name='viewers',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='viewers',
            name='viewer_comments',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
